name: Tag PAT Main
on:
  workflow_dispatch:
    inputs:
      openshiftServer:
        description: 'Your Artifactory URL'
        default: '10.0.0.1:8081'  
      openshiftToken:
        description: 'Your openshift token'
        default: 'TOKEN String'
  push:
    tags:
      - tag-pat/main/*

jobs:
  work:
    name: Some Work
    runs-on: ubuntu-latest

    env:
      tag: ${GITHUB_REF#refs/tags/tag-pat/main/}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - run: echo "Some Main work"
      - run: echo "Tag ${{ env.tag }}"
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git tag -a tag-pat/work/${{ env.tag }} -m "${{ env.tag }}"

          git push "https://$GITHUB_ACTOR:${{ secrets.PAT_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" tag-pat/work/${{ env.tag }} -f
