name: Workflow work

on:
  workflow_run:
    workflows: [ "Workflow main" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  work:
    name: Some Work
    runs-on: ubuntu-latest
    steps:
      - run: echo "Some work"