name: Workflow Work

on:
  workflow_run:
    workflows: [ "Workflow Main" ]
    types:
      - completed
  workflow_dispatch:
    inputs:
        artifactoryUrl:
          description: 'Your Artifactory URL'
          default: 'myArtifactoryURL.com'  
        artifactoryName:
          description: 'Your Repo Name'
          default: 'myRepoName'
        artifactoryPath:
          description: 'Your Repo path'
          default: 'myRepoPath' 
        artifactoryToken:
          description: 'Your Repo AccessToken'
          default: 'TOKEN String'

jobs:
  work:
    name: Some Workflow Work
    runs-on: ubuntu-latest
    steps:
      - run: echo "Some work"
